config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'projects#index'
resources :projects do
resources :tasks, only: [:create, :destroy]
post 'projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'  
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  # taskと1対多で紐付く
  has_many :tasks
  # 「project」を未入力の状態では保存できなくなる
  # validates :title, presence: true
  # エラーメッセージを定義（メッセージは独自定義）
  validates :title,
  presence: { message: "入力してください" },
  length: { minimum: 3, message: "短すぎます" }
end

app/models/task.rb
class Task < ApplicationRecord
  # projectに属しているという情報
  belongs_to :project
  validates :title,
    presence: true
    scope :unfinished, -> { where(done: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # 共通処理を定義（各Actionでは'set_project'が呼ばれますよ、という宣言)
  # 別途'set_project'という関数を定義する
  # 全Actionに適用するわけではないので、'only'で実行するActionを限定する
  before_action :set_project, only: [:show, :edit, :updsate, :destroy]

  # indexアクションを追加
  def index
   # @をつけた変数はviewでそのまま使用可能
   # Projectの全データを引っ張ってくる
    @projects = Project.all
  end

  # showアクションを追加
  def show
    @project = Project.find(params[:id])
  end

  # newアクションを追加
  def new
    @project = Project.new
  end

  # createアクションを追加
  def create
    # Formからの入力値を受け取る
    @project = Project.new(project_params)
    # データの保存
    if @project.save
    # saveがtrueだったらHOMEへ移動
      redirect_to projects_path
    else
    # saveがfalseだったら入力フォームに戻る
      render 'new'
    end
  end

    # editアクションを追加
    def edit
      @project = Project.find(params[:id])
    end

    # updateアクションを追加
    def update
      @project = Project.find(params[:id])
      if @project.update(project_params)
        redirect_to projects_path
      else
        render 'edit'
      end
    end

    # Destroyアクションを追加
    def destroy
      @project = Project.find(params[:id])
      # 削除
      @project.destroy
      # Homeへリダイレクト
      redirect_to projects_path
    end

  # project_params を定義
  private
   def project_params
     # projectでわたってきたもののうち、titleだけ使用
     params[:project].permit(:title)
   end
     # before_actionで定義した処理の実装
   def set_project
    @project = Project.find(params[:id])
   end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # createアクションを追加
  def create
    # 画面からわたってきたIDからprojectをfindする
    @project = Project.find(params[:project_id])
    # taskを登録
    @task = @project.tasks.create(tasks_params)
    # 遷移先はプロジェクト詳細画面
    redirect_to project_path(@project.id)
  end

  # destroyアクションを追加
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end
  
  # toggleアクションを追加
  def toggle
    render nothing: true
    @task = Task.find(params[:id])
  # タスクのdoneの値をひっくり返す
    @task.done = !@task.done
    @task.save

private
   # task_paramsを定義
   def tasks_params
   # taskでわたってきたもののうち、titleだけ使用
    params[:task].permit(:title)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to "HOME", "/" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<p>
  <%= f.label ;title %><br>
  <%= f.text_field :title %><br>

  <% if @project.errors.any? %>
    <%= @@project.errors.messages[:title][0] %>
  <% end %>

</p>

<p>
  <%= submit %><br>
</p>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= form_for @project do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <!-- エラー存在チェック-->
  <% if @project.errors.any? %>
  <!-- エラー情報の習得-->
    <%= @project.errors.messages[:title][0] %>
  <% end %>

</p>

<p>
  <%= f.submit %><br>
</p>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
  <% @projects.each do |project| %>
  <li>
    <%= link_to  project.title, project_path(project.id) %>
    <%= link_to project.title, project_path(project.id) %>
    <%= project.tasks.unfinished.count %>/<%= project.tasks.count %>
    <%= link_to "[Edit]", edit_project_path(project.id) %>
    <!-- 削除リンク -->
    <!-- methodにdeleteを指定することで、Destoroyアクションと紐づけられる -->
    <!-- dateで確認メッセージを指定 -->
    <%= link_to "[Delete]", project_path(project.id), method: :delete, data: { confirm: "are you sure?" } %>
  </li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_project_path %></p>

app/views/projects/new.html.erb
<h1>Add New</h1>
<%= form_for @project do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <!-- エラーチェック-->
  <% if @project.errors.any? %>
  <!-- エラー情報の取得-->
  <%= @project.errors.inspect %>
  <% end %>
</p>

<p>
  <%= f.submit %><br>
</p>

<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<ul>
  <!-- projectに紐付くtaskがあるだけループする -->
  <% @project.tasks.each do |task| %>
  <li>
    <!-- 進捗管理チェックボックス -->
    <!-- idやvalueは不要なのでオプションはブランク -->
    <!-- task.doneがチェックの有無を意味する(ture,false) -->
    <!-- taskのIDとprojectのIDを属性として保持させて使えるようにする -->
    <%= check_box_tag '','', task.done, { 'data-id' => task.id, 'data-project_id' => task.project_id } %>
    <!-- taskのtitleを表示 -->
    <%= task.title %>
  </li>
    <!-- taskのtitleを表示 -->
    <%= task.title %>
    <!-- 削除リンク（taskのプロジェクトIDとtaskIDを取得) -->
    <%= link_to "[Delete]", project_task_path(task.project_id, task.id), method: :delete, data: { confirm: "are you sure" } %>
  </li>
  <% end %>

  <!-- 新規タスク登録フォーム -->
  <li>
    <%= form_for [@project, @project.tasks.build] do |f| %>
    <%= f.text_field :title %>
    <%= f.submit %>
    <% end %>
  </li>
</ul>

<!-- jqueryの機能を使ってチェックボックスの制御を行う -->
<script type="text/javascript">
  $(function() {
    $("input[type=checkbox]").click(function() {
        $.post('/projects/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle')
    })
  })
</script>